### ISSUE TITLE
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.

### ISSUE THREAD

**Issue by jroman** [emartinez-dev/renfe-bot#14]
Hola,

mil gracias por este bot!

Al poco de pasar la primera consulta me salta el error que te pongo al final. ¿Alguna idea de solución? ¿algo que pueda cambiar en el código?

```
Ya estoy corriendo! Corre a Telegram e interactúa conmigo
Searching for trains...


Traceback (most recent call last):
  File "renfe-bot.py", line 211, in <module>
    bot.polling()
  File "~/.local/lib/python3.8/site-packages/telebot/__init__.py", line 1045, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "~/.local/lib/python3.8/site-packages/telebot/__init__.py", line 1120, in __threaded_polling
    raise e
  File "~/.local/lib/python3.8/site-packages/telebot/__init__.py", line 1082, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "~/.local/lib/python3.8/site-packages/telebot/util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "~/.local/lib/python3.8/site-packages/telebot/util.py", line 90, in run
    task(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/telebot/__init__.py", line 6793, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "renfe-bot.py", line 45, in send_retry
    search_trains(message, user_params)
  File "renfe-bot.py", line 196, in search_trains
    scrap = Watcher(query, filter)
  File "/spare/spare_other/develop/renfebot/renfe-bot/watcher/watcher.py", line 20, in __init__
    self.scraper.find_trains(self.query)
  File "/spare/spare_other/develop/renfebot/renfe-bot/scraper/scraper.py", line 81, in find_trains
    page.click("text=Buscar billete")
  File "~/.local/lib/python3.8/site-packages/playwright/sync_api/_generated.py", line 10189, in click
    self._sync(
  File "~/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
  File "~/.local/lib/python3.8/site-packages/playwright/_impl/_page.py", line 694, in click
    return await self._main_frame.click(**locals_to_params(locals()))
  File "~/.local/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "~/.local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
  File "~/.local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 492, in wrap_api_call
    return await cb()
  File "~/.local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.
```

**Comment by emartinez-dev** [comment]
Hola!
Perdona, hacía mucho tiempo que no lo utilizaba y parece que han estado trabajando mucho en la web. Ya está arreglado, espero que te sirva!
